# Generated by Django 5.0.4 on 2025-11-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='msg_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transmission',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transmission',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transmission',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('RECEIVED', 'Received'), ('FAILED', 'Failed')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='device',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='role',
            field=models.CharField(choices=[('TX', 'Transmitter'), ('RX', 'Receiver'), ('RELAY', 'Relay')], max_length=10),
        ),
    ]
