# Generated by Django 4.2.26 on 2025-11-14 08:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transmission_msg_id_transmission_received_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeaterDevice',
            fields=[
                ('device', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('friendly_name', models.CharField(blank=True, default='', max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'repeater_device',
            },
        ),
        migrations.CreateModel(
            name='RepeaterStatus',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='status', serialize=False, to='api.repeaterdevice')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('signal_strength', models.IntegerField(blank=True, null=True)),
                ('tx_power', models.IntegerField(blank=True, null=True)),
                ('rx_total', models.IntegerField(default=0)),
                ('tx_total', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('uptime_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'repeater_status',
            },
        ),
        migrations.CreateModel(
            name='RepeaterActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('msg_id', models.IntegerField()),
                ('message', models.TextField()),
                ('action', models.CharField(choices=[('received', 'received'), ('retransmitted', 'retransmitted')], max_length=16)),
                ('voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('signal_strength', models.IntegerField(blank=True, null=True)),
                ('tx_power', models.IntegerField(blank=True, null=True)),
                ('rx_total', models.IntegerField(default=0)),
                ('tx_total', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.repeaterdevice')),
            ],
            options={
                'db_table': 'repeater_activity',
                'indexes': [models.Index(fields=['device', 'msg_id'], name='idx_device_msgid'), models.Index(fields=['timestamp'], name='idx_timestamp'), models.Index(fields=['device'], name='idx_device')],
            },
        ),
    ]
